# LightDM GTK+ Greeter Configuration
# Login screen for OffTopic Linux

[greeter]
# Background
background = /usr/share/backgrounds/offtopic/offtopic-dark.jpg

# Theme
gtk-theme-name = Adwaita-dark
icon-theme-name = Papirus-Dark

# Font
gtk-font-name = Sans 10

# Cursor
cursor-theme-name = Adwaita

# Logo
# uncomment and set your logo
# logo = /usr/share/pixmaps/offtopic-logo.png

# User list
show-icons = true
hide-users = false
show-manual-login = true
allow-guest = false

# Position
layout = 
default-user-image = /usr/share/pixmaps/avatar-default.png
